version: 2
jobs:
  build:
    docker:
      - image: quay.io/fossa/fossa-cli:latest
    working_directory: /home/fossa/go/src/github.com/fossas/fossa-cli
    environment:
      TEST_RESULTS: /tmp/test-results
      ARTIFACTS: /tmp/artifacts
    steps:
      - checkout
      - run:
          name: Make folders
          command: |
            mkdir -p $TEST_RESULTS
            mkdir -p $ARTIFACTS
      - restore_cache:
          keys:
            - v1-gopkg-cache-{{ checksum "Gopkg.lock" }}
      - run: go get github.com/jstemmer/go-junit-report
      - run:
          name: Compile CLI
          command: |
            # Invalidate pkg cache for FOSSA CLI binary
            rm -rf /home/fossa/go/pkg/linux_amd64/github.com/fossas/fossa-cli
            dep ensure
            make
      - save_cache:
          key: v1-gopkg-cache-{{ checksum "Gopkg.lock" }}
          paths:
            - "/home/fossa/go/pkg"
            - "/home/fossa/go/src/github.com/fossas/fossa-cli/vendor"
      - run:
          name: Run integration test
          command: |
            # Load shell helpers (e.g. sdkman)
            source /home/fossa/.bashrc
            # Run tests
            go test ./builders | go-junit-report > ${TEST_RESULTS}/go-test-report.xml
      - run:
          name: Run FOSSA build
          command: |
            fossa --debug 2>$ARTIFACTS/fossa-build-stderr
      - run:
          name: Run FOSSA license check
          command: |
            fossa test --debug 2>$ARTIFACTS/fossa-test-stderr
      - store_test_results:
          path: /tmp/test-results
      - store_artifacts:
          path: /tmp/artifacts
